language: perl6
perl6:
    - latest

install:
    - rakudobrew build-panda
    - panda update && panda install File::Temp File::Which File::Zip Find::Bundled HTTP::UserAgent JSON::Tiny MIME::Base64 URI::Encode

before_script:  # firefox tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
