sudo: required

os:
  - linux
  - osx

before_install:
  - echo $TRAVIS_OS_NAME
  # Install PhantomJS on MacOSX using homebrew
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                  ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install phantomjs       ; fi
  # Show PhantomJS version
  - phantomjs --version
  - phantomjs --webdriver=5555 --webdriver-loglevel=DEBUG &

script: prove -v -e "perl6 -Ilib" t/
