sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2016.02
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build panda
  - panda installdeps .

before_script:
  # Start xvfb for Firefox headless testing and give it some time to start
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then "export DISPLAY=:99.0"         ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then "sh -e /etc/init.d/xvfb start" ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sleep 3                        ; fi
  # Show PhantomJS version
  - phantomjs --version

script: prove -v -e "perl6 -Ilib" t/
