language: perl6
perl6:
    - latest

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
    - rakudobrew build-panda
    - panda update && panda install File::Which HTTP::UserAgent JSON::Tiny MIME::Base64 URI::Encode
