sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2016.02
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build panda
  - panda installdeps .

before_script:
  # Firefox tests
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # give xvfb some time to start
  - sleep 3

script: prove -v -e "perl6 -Ilib" t/
